#versao do compose
version: "3"

services:
  react-container:
    build:
      context: ./
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    container_name: react-container
    ports:
      - 2000:80
      - 2020:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    entrypoint: npm run start
